#!/bin/bash
# Hook to block git commits and gh commands containing Claude self-citations

# Read JSON input from stdin
input=$(cat)

# Fast exit if input doesn't contain git commit or gh command patterns
if ! echo "$input" | grep -qE '(git commit|"command":\s*"gh\s)'; then
    exit 0
fi

# Extract tool_name and command
tool_name=$(echo "$input" | jq -r '.tool_name // empty')
command=$(echo "$input" | jq -r '.tool_input.command // empty')

# Only check Bash commands
if [[ "$tool_name" != "Bash" ]]; then
    exit 0
fi

# Only check git commit and gh commands
if [[ ! "$command" =~ git\ commit ]] && [[ ! "$command" =~ ^gh\  ]]; then
    exit 0
fi

# Check for Claude self-citation patterns
if echo "$command" | grep -qiE "(Co-Authored-By:.*Claude|Generated with.*Claude Code|noreply@anthropic\.com|Generated by Claude)"; then
    echo "Blocked: Command contains Claude self-citation." >&2
    echo "Please remove references like:" >&2
    echo "  - 'Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>'" >&2
    echo "  - 'Generated with [Claude Code](...)'" >&2
    echo "  - Any other Claude attribution" >&2
    exit 2
fi

# Allow the command
exit 0
