#!/bin/bash
# Hook to block git commits and gh commands containing Claude self-citations
#
# Why this exists: Claude is awesome, but I don't need Anthropic's
# cattle brand on everything I do with it.

# Enable debug mode by setting CLAUDE_HOOK_DEBUG=1
DEBUG=${CLAUDE_HOOK_DEBUG:-0}

debug() {
    if [[ "$DEBUG" -eq 1 ]]; then
        echo "[DEBUG] $*" >&2
    fi
}

# Read JSON input from stdin (Claude Code sends complete JSON object)
input=$(cat 2>/dev/null) || {
    debug "Failed to read stdin"
    exit 0  # Allow on read failure
}

# Validate we got input
if [[ -z "$input" ]]; then
    debug "Empty input received"
    exit 0
fi

debug "Received input (first 200 chars): ${input:0:200}..."

# Extract tool_name using jq with error handling
tool_name=$(echo "$input" | jq -r '.tool_name // empty' 2>/dev/null)
if [[ $? -ne 0 ]]; then
    debug "jq failed to parse tool_name - allowing command"
    exit 0
fi

debug "Tool name: $tool_name"

# Only check Bash commands
if [[ "$tool_name" != "Bash" ]]; then
    debug "Not a Bash command - allowing"
    exit 0
fi

# Extract command from tool_input.command
command=$(echo "$input" | jq -r '.tool_input.command // empty' 2>/dev/null)
if [[ $? -ne 0 ]] || [[ -z "$command" ]]; then
    debug "jq failed to extract command - allowing"
    exit 0
fi

debug "Command (first 200 chars): ${command:0:200}"

# Only check git commit, git push, and gh pr/issue commands
if [[ ! "$command" =~ git[[:space:]]+commit ]] &&
   [[ ! "$command" =~ ^gh[[:space:]]+(pr|issue)[[:space:]]+(create|edit) ]]; then
    debug "Not a git commit or gh pr/issue command - allowing"
    exit 0
fi

debug "Checking for Claude self-citations..."

# Check for Claude self-citation patterns (case-insensitive)
# Note: jq -r extracts the string with actual newlines, so grep works normally
# Patterns to block:
# - Co-Authored-By: Claude...
# - Generated with Claude Code
# - noreply@anthropic.com
# - Generated by Claude
# - Claude Sonnet version references
if echo "$command" | grep -qiE "(Co-Authored-By:.*Claude|Generated with.*Claude Code|noreply@anthropic\.com|Generated by Claude|claude sonnet [0-9.]+)"; then
    # Block the command with detailed error message (exit code 2)
    cat >&2 << 'EOF'
❌ Blocked: Claude self-citation detected

Found Claude attribution in commit message or PR description.
Please remove references like:
  • Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>
  • 🤖 Generated with [Claude Code](...)
  • Generated by Claude

Per CLAUDE.md guidelines: Do not cite yourself in commit messages.

To debug, set CLAUDE_HOOK_DEBUG=1 and retry the command.
EOF
    exit 2
fi

debug "No citations found - allowing command"

# Allow the command (exit code 0)
exit 0
